core/urls.py
# core/urls.py

from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('parent/', views.parent, name='parent_dashboard'),

    # Child management
    path('dashboard/children/', views.children_list, name='children_list'), 
    path('dashboard/children/register/', views. child_registration, name='register_child'),
    path('dashboard/children/<uuid:child_id>/edit/', views.edit_child, name='edit_child'),
    path('dashboard/children/<uuid:child_id>/delete/', views.delete_child, name='delete_child'),

    # School management
    path('dashboard/municipality/', views.municipality_dashboard, name='municipality_dashboard'),
    path('dashboard/teacher/', views.teacher_dashboard, name='teacher_dashboard'),
    
    # APK management
    path('dashboard/apk/', views.apk_list, name='apk_list'),
    path('dashboard/apk/upload/', views.upload_apk, name='upload_apk'),
    path('dashboard/apk/<uuid:apk_id>/edit/', views.edit_apk, name='edit_apk'),
    

    # User profile image update
    path('dashboard/profile/image/update/', views.update_profile_image, name='update_profile_image'),
     path("dashboard/profile/", views.profile_view, name="profile"),
       
    #path('register/parent/', views.parent_register, name='parent_register'),
    path('check-whatsapp-number/', views.check_whatsapp_number, name='check_whatsapp_number'),
    path("register/parent/", views.ParentRegisterView.as_view(), name="parent_register"),
    path('admin/', views.admin_parent_child_list, name='admin'),
    path("login/", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("dashboard/admin/", views.moe_admin_dashboard, name="moe_admin_dashboard"),
    path("dashboard/users/", views.UserManagementView.as_view(), name="user_management"),
    path('dashboard/parents/', views.parent_list, name='parent_list'),
        path('dashboard/parents/export-pdf/', views.export_parents_pdf, name='export_parents_pdf'),
    path('dashboard/logs/', views.AppUsageLogListView.as_view(), name='app_usage_logs'),
    path('reports/children/', views.ChildrenReportView.as_view(), name='children_report'),
    #path('reports/apk/', views.APKReportView.as_view(), name='apk_report'),
      # AJAX endpoints
    path("ajax/load-administrative-posts/", views.LoadAdministrativePosts.as_view(), name="ajax_load_admin_posts"),
    path("ajax/load-sucos/", views.LoadSucos.as_view(), name="ajax_load_sucos"),
    path("ajax/load-aldeias/", views.LoadAldeias.as_view(), name="ajax_load_aldeias"),
    path("dashboard/register/user/", views.register_user, name="register_user"),


    #APk
    path("dashboard/apk/latest/", views.LatestApkView.as_view(), name="latest_apk"),
        # Password reset URLs
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(template_name="registration/password_reset_form.html"),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_confirm.html"),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_complete.html"),
        name="password_reset_complete",
    ),
]

haap_platform/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/footer.html
<!-- partials/footer.html -->
<footer class="app-footer py-3 bg-light border-top">
  <div class="container text-center small text-muted">

    <div class="mb-1">
      Created by <strong>World Mosaic</strong> for and in consultation with 
      <strong>Timor-Leste Ministry of Education</strong> as part of the 
      <em>Mary Mackillop Today EdTech for Early Learning (ETEL)</em> initiative 
      sponsored by <strong>O'Brien Foundation Australia</strong>.
    </div>

    <div>
      &copy; {{ "now" | date:"%Y" }} World Mosaic. All rights reserved.
    </div>

  </div>
</footer>

templates/partials/header.html
<!-- partials/header.html -->
 {% load static %}
<nav class="app-header navbar navbar-expand bg-body">
  <!--begin::Container-->
  <div class="container-fluid">
    <!--begin::Start Navbar Links-->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-lte-toggle="sidebar" href="#" role="button">
          <i class="bi bi-list"></i>
        </a>
      </li>
      <li class="nav-item d-none d-md-block"><a href="#" class="nav-link">Home</a></li>
      <li class="nav-item d-none d-md-block"><a href="#" class="nav-link">Kontaktu</a></li>
    </ul>
    <!--end::Start Navbar Links-->
    <!--begin::End Navbar Links-->
    <ul class="navbar-nav ms-auto">
      <!--begin::Navbar Search-->
      <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
          <i class="bi bi-search"></i>
        </a>
      </li>
      <!--end::Navbar Search-->
      <!--begin::Messages Dropdown Menu-->
    
      <!--end::Notifications Dropdown Menu-->
      <!--begin::Fullscreen Toggle-->
      <li class="nav-item">
        <a class="nav-link" href="#" data-lte-toggle="fullscreen">
          <i data-lte-icon="maximize" class="bi bi-arrows-fullscreen"></i>
          <i data-lte-icon="minimize" class="bi bi-fullscreen-exit" style="display: none"></i>
        </a>
      </li>
      <!--end::Fullscreen Toggle-->
      <!--begin::User Menu Dropdown-->
     <li class="nav-item dropdown user-menu">
  <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
    <img
      src="{{ user.image.url }}"
      class="user-image rounded-circle shadow"
      alt="User Image"
    />
    <span class="d-none d-md-inline">{{ user.get_full_name }}</span>
  </a>
  <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-end">
    <!--begin::User Image-->
            <li class="user-header text-bg-primary">
              <img
                src="{{ user.image.url }}"
                class="rounded-circle shadow"
                alt="User Image"
              />
              <p>
                {{ user.get_full_name }} - {{ user.get_role_display }}
                <small>Sai membru desde {{ user.date_joined|date:"M. Y" }}</small>
              </p>
            </li>
            <!--end::User Image-->

            <!--begin::Menu Body-->
                <li class="user-body">
          <div class="row">
            <!-- Common menu items for all roles -->
            <div class="col-4 text-center">
              <a href="{% url 'core:profile'%}">Hau nia Profile</a>
            </div>
            <div class="col-4 text-center">
              <a href="{% url 'core:update_profile_image' %}">Hau nia Photo</a>
            </div>

            <!-- Role-specific menu item -->
            {% if user.role == "parent" %}
              <div class="col-4 text-center"><a href="#">Hau nia oan</a></div>

            {% elif user.role == "teacher" %}
              <div class="col-4 text-center"><a href="#">Hau nia Aulas</a></div>

            {% elif user.role == "municipality_analyst" %}
              <div class="col-4 text-center"><a href="#">Analytics</a></div>

            {% elif user.role == "moe_admin" %}
              <div class="col-4 text-center"><a href="#">Utilizadores</a></div>
            {% endif %}
          </div>
        </li>


    <!--end::Menu Body-->

          <!--begin::Menu Footer-->
          <li class="user-footer">
            <!-- <a href="{% url 'core:update_profile_image' %}" class="btn btn-default btn-flat">Profile</a> -->
            <a href="{% url 'core:logout' %}" class="btn btn-default btn-flat float-end">Sair</a>
          </li>
          <!--end::Menu Footer-->
        </ul>
      </li>

      <!--end::User Menu Dropdown-->
    </ul>
    <!--end::End Navbar Links-->
  </div>
  <!--end::Container-->
</nav>
<!--end::Header-->

templates/partials/navbar.html
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
    </li>
  </ul>
</nav>

templates/partials/sidebar.html
{% load static %}
<!-- partials/sidebar.html -->
<aside class="app-sidebar bg-body-secondary shadow" data-bs-theme="dark">
  <!-- Sidebar Brand -->
  <div class="sidebar-brand">
    <a href="#" class="brand-link">
      <img
        src="{% static 'img/logo-ori.png' %}"
        alt="HAAP Logo"
        class="brand-image opacity-75 shadow"
      />
      <span class="brand-text fw-light">HAAP Dashboard</span>
    </a>
  </div>

  <!-- Sidebar Wrapper -->
  <div class="sidebar-wrapper">
    <nav class="mt-2">
      <ul
        class="nav sidebar-menu flex-column"
        data-lte-toggle="treeview"
        role="navigation"
        aria-label="Main navigation"
        data-accordion="false"
        id="navigation"
      >

        <!-- Dashboard -->
      {% if user.role == "moe_admin" %}
        <li class="nav-item">
          <a href="{% url 'core:moe_admin_dashboard' %}" class="nav-link active">
            <i class="nav-icon bi bi-speedometer2"></i>
            <p>Admin Dashboard </p>
          </a>
        </li>
        {% elif user.role == "parent" %}
        <li class="nav-item">
          <a href="{% url 'core:children_list' %}" class="nav-link active">
            <i class="nav-icon bi bi-speedometer2"></i>
            <p>Dashboard ba Pais</p>
          </a>
        </li>
      {% elif user.role == "municipality_analyst" %}
        <li class="nav-item">
          <a href="{% url 'core:municipality_dashboard' %}" class="nav-link active">
            <i class="nav-icon bi bi-bar-chart"></i>
            <p>Dashboard ba Munisipalidade</p>
          </a>
        </li>
      {% elif user.role == "teacher" %}
        <li class="nav-item">
          <a href="{% url 'core:teacher_dashboard' %}" class="nav-link active">
            <i class="nav-icon bi bi-journal-text"></i>
            <p>Dashboard ba Professor</p>
          </a>
        </li>
      {% endif %}

        {% if user.role == "moe_admin" %}
          <!-- User Management (Admin only) -->
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon bi bi-people-fill"></i>
              <p>
                Utilizadores
                <i class="nav-arrow bi bi-chevron-right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'core:user_management'%}" class="nav-link">
                  <i class="nav-icon bi bi-circle"></i>
                  <p>Utilizadores </p>
                </a>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="nav-icon bi bi-circle"></i>
                  <p>Inan aman</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="nav-icon bi bi-circle"></i>
                  <p>Professor</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="nav-icon bi bi-circle"></i>
                  <p>analista munisipal</p>
                </a>
              </li>
            </ul>
          </li>

          <!-- APK Versions -->
          <li class="nav-item">
            <a href="{% url 'core:apk_list' %}" class="nav-link">
              <i class="nav-icon bi bi-phone"></i>
              <p>Versoes APK</p>
            </a>
          </li>

          <!-- System Settings -->
          <li class="nav-header">SYSTEMA</li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon bi bi-gear-fill"></i>
              <p>Settings</p>
            </a>
          </li>
        {% elif user.role == "parent" %}
          <!-- Children for Parents -->
          <li class="nav-item">
            <a href="{% url 'core:children_list' %}" class="nav-link">
              <i class="nav-icon bi bi-person-badge"></i>
              <p>Hau nia oan</p>
            </a>
          </li>
           <!-- APK Versions -->
          <li class="nav-item">
              <a href="{% url 'core:latest_apk' %}" class="nav-link">
                  <i class="nav-icon bi bi-phone"></i>
                  <p>
                      Download APK
                      {% if versions %}
                          <span class="badge bg-danger ms-1">Foun</span>
                      {% endif %}
                  </p>
              </a>
          </li>

        {% elif user.role == "municipality_analyst" %}
          <!-- Municipality Dashboard -->
          <li class="nav-item">
            <a href="{% url 'core:municipality_dashboard' %}" class="nav-link">
              <i class="nav-icon bi bi-bar-chart"></i>
              <p>Dashboard</p>
            </a>
          </li>
        {% elif user.role == "teacher" %}
          <!-- Teacher Dashboard -->
          <li class="nav-item">
            <a href="{% url 'core:teacher_dashboard' %}" class="nav-link">
              <i class="nav-icon bi bi-person-badge"></i>
              <p>Dashboard ba Professor</p>
            </a>
          </li>
        {% endif %}

        <!-- Logs (all roles can see) -->
        <li class="nav-item">
          <a href="{% url 'core:app_usage_logs' %}" class="nav-link">
            <i class="nav-icon bi bi-gear-fill"></i>
            <p>Logs</p>
          </a>
        </li>

        <!-- Logout -->
        <li class="nav-item">
          <a href="{% url 'core:logout' %}" class="nav-link">
            <i class="nav-icon bi bi-box-arrow-right"></i>
            <p>Sair</p>
          </a>
        </li>
      </ul>
    </nav>
  </div>
</aside>